# @name signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Norman Ozzy",
    "nickname": "Green bat",
    "email": "norman@ozzy.com",
    "password": "ihatesun",
    "role": "admin"
}

###

# @name login

POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "norman@ozzy.com",
    "password": "ihatesun"
}

###

# @name edit

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE1ODA3MjRlLTEyZWItNDllYy05MDdiLWVhZmZiM2ViMmZkMCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2Mjc0ODM1OSwiZXhwIjoxNjYyNzQ4OTU5fQ.WBZiamLzyVGl3PAjXXZ9qG9NvkoMrP0vLgKUar65NmQ

PUT http://localhost:3003/user/edit
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Norman"
}

###

# @name profile

GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: {{token}}