# @name signup
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Cosmodev",
    "email": "cosmo@dev.com",
    "password": "123456"
}

###

# @name login
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "cosmo@dev.com",
    "password": "123456"
}

###

# @name pegarProprioPerfil
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhmNWFhOTc1LTRiOWYtNDg0My1iNWUzLTM5OTExMTY2ZTNjNyIsImlhdCI6MTY2MzM0OTM0OSwiZXhwIjoxNjYzNDM1NzQ5fQ.s20HTRwsabfcIJQ6sAenu6Yk4NGF2Rz_j-cpDaA0jOM

###

# @name pegarPerfilDeOutroUsuario
GET http://localhost:3003/user/7079b8e4-95cd-48aa-82a9-77454e94b789
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhmNWFhOTc1LTRiOWYtNDg0My1iNWUzLTM5OTExMTY2ZTNjNyIsImlhdCI6MTY2MzM0OTM0OSwiZXhwIjoxNjYzNDM1NzQ5fQ.s20HTRwsabfcIJQ6sAenu6Yk4NGF2Rz_j-cpDaA0jOM

###

# @name criarReceita
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhmNWFhOTc1LTRiOWYtNDg0My1iNWUzLTM5OTExMTY2ZTNjNyIsImlhdCI6MTY2MzM0OTM0OSwiZXhwIjoxNjYzNDM1NzQ5fQ.s20HTRwsabfcIJQ6sAenu6Yk4NGF2Rz_j-cpDaA0jOM

{
    "title": "Beijinho",
    "description": "Numa panela, misture o leite condensado, a manteiga e o coco ralado. Leve ao fogo e misture por aproximadamente 15 minutos. Retire a mistura do fogo e deixe amornar. Modele a massa em formato de bolinhas, passe pelo açúcar cristal ou coco ralado e finalize com cravos-da-índia."
}

###

# @name pegarReceita
GET http://localhost:3003/recipe/e503543c-d121-4ed8-9fa6-3e85587e740d
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkOGE2MWIzLWVhZjUtNGI2ZC1hMmYwLTllNjM1ODU5Mzc2YiIsImlhdCI6MTY2MzM2NTEzNywiZXhwIjoxNjYzNDUxNTM3fQ.SgSsKthPwpkKTFtj6qBBYy6TEvTBHuAny8hIJhrrA-0

###

# @name follow
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkOGE2MWIzLWVhZjUtNGI2ZC1hMmYwLTllNjM1ODU5Mzc2YiIsImlhdCI6MTY2MzM1NDU0NywiZXhwIjoxNjYzNDQwOTQ3fQ.IpBY9AudGnY7iJyaEqcLO95bcIIUGYXtuWhLYaBS-TE

{
    "userToFollowId": "7079b8e4-95cd-48aa-82a9-77454e94b789"
}

###

# @name unfollow
POST http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkOGE2MWIzLWVhZjUtNGI2ZC1hMmYwLTllNjM1ODU5Mzc2YiIsImlhdCI6MTY2MzM1NDU0NywiZXhwIjoxNjYzNDQwOTQ3fQ.IpBY9AudGnY7iJyaEqcLO95bcIIUGYXtuWhLYaBS-TE

{
    "userToUnfollowId": "7079b8e4-95cd-48aa-82a9-77454e94b789"
}

###

# @name feed
GET http://localhost:3003/user/feed
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkOGE2MWIzLWVhZjUtNGI2ZC1hMmYwLTllNjM1ODU5Mzc2YiIsImlhdCI6MTY2MzM1NDU0NywiZXhwIjoxNjYzNDQwOTQ3fQ.IpBY9AudGnY7iJyaEqcLO95bcIIUGYXtuWhLYaBS-TE

