# @name Create
POST http://localhost:3003/competition
Content-Type: application/json

{
    "name": "Nicole Run World Tour",
    "type": "HUNDRED_DASH"
}

###

# @name Result
POST http://localhost:3003/competition/1
Content-Type: application/json

###

# @name Try
PUT http://localhost:3003/result/1
Content-Type: application/json

###

# @name Finish
PUT http://localhost:3003/competition/1/finish
Content-Type: application/json

###

# @name Ranking
GET http://localhost:3003/competition/1/ranking
Content-Type: application/json